name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace webhook placeholder
        run: |
          sed -i "s|{{WEBHOOK_URL}}|${{ secrets.MAKE_WEBHOOK_URL }}|g" docs/booking.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Or your site's build directory if using a framework

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
